name: DAST-SVD Onboarding Action

description: Reusable action for DAST onboarding with Burp Suite

inputs:
  app_name:
    description: 'Application name'
    required: true
  url:
    description: 'Target URL for the DAST scan'
    required: true
  config:
    description: 'Scan configuration'
    required: true
  dast_api_host:
    description: 'DAST API Host URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: DAST-Security-Burp-Onboarding
      run: |
        echo "=================================================="
        echo "========--- DAST - Burp Scan: Start ---========"
        echo "=================================================="

        curl -k -w "\n" -X POST ${{ inputs.dast_api_host }}/api/${{ secrets.DASTAPIKEY }}/v0.1/scan \
        -d '{"name":"${{ inputs.app_name }}","scan_configurations":[{"name":"${{ inputs.config }}","type":"NamedConfiguration"}],"urls":["${{ inputs.url }}"]}' -D headers.txt

        cat headers.txt

        if grep -q "201 Created" headers.txt; then
          echo "SUCCESS: DAST Onboarding for App-id - ${{ inputs.app_name }} is completed" >> emailbody.txt
        else
          echo "FAILURE: DAST Onboarding for App-id - ${{ inputs.app_name }} failed with errors" >> emailbody.txt
          exit 1
        fi

        echo "=================================================="
        echo "========--- DAST - Burp Scan: End ---========"
        echo "=================================================="

