name: DAST-SVD Onboarding Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast_svd_onboarding:
    runs-on: pru-gisp-all-nprd-linux-runner-01
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DAST Onboarding Action
        uses: ./.github/actions/dast-svd-onboarding-action.yml
        with:
          app_name: GWISP-ctly-security
          url: https://sample-vmapi.aks-lb1-sgrsss-uat-az1-tzbgb5.pru.intranet.asia
          config: Pru_Audit_Policy
          dast_api_host: https://dast.pru.intranet.asia

      - name: End Workflow
        if: ${{ always() }}
        run: echo "Workflow completed."
